# Generated by Django 6.0.1 on 2026-03-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_flavorprofile_alter_appuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='token',
            field=models.CharField(default='3f49edfd021daf5e6295ddd2f34636eb', max_length=64, unique=True),
        ),
    ]
