# Generated by Django 6.0.1 on 2026-03-24 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_usersession_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientaromarelation',
            name='aroma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.aroma'),
        ),
        migrations.AlterField(
            model_name='ingredientflavourrelation',
            name='flavour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.flavour'),
        ),
        migrations.AlterField(
            model_name='usersession',
            name='token',
            field=models.CharField(default='3f41e73c284e5583f0652f1c1d73abc5', max_length=64, unique=True),
        ),
    ]
